### PR TITLE
Add github workflow for Azure

### LINKED ISSUE #215: Add github workflow to deploy to azure as static web app
@mohit038 could you please add a workflow (as a PR, maybe using https://github.com/JabRef/JabRefOnline/blob/main/.github/workflows/deploy.yml as a basis and incorporating https://github.com/JabRef/JabRefOnline/issues/577). Then I will handle the necessary config in azure and add the secrets to github.

### PR DESCRIPTION
**Pull request by mohit038**
fixes #215

### CODE REVIEW

**Comment by mohit038** [comment]
@tobiasdiez, Please change the index document name from the default index.html to taskpane.html in the Azure portal.

see the 6th point.
https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code#using-visual-studio-code-to-publish

**Comment by tobiasdiez** [comment]
In contrast to "Azure Storage" apps, "Static Web Apps" don't seem to have this option. I've found https://github.com/Azure/static-web-apps/issues/232 which discusses the same issue and recommends to add an empty index.html. Could you please try this?

**Comment by tobiasdiez** [comment]
But maybe it's already enough to change https://github.com/JabRef/JabRef-Word-Addin/blob/4377c36273c19e5e62537990450faf7a554820f4/webpack.config.js#L76 to use `index.html` instead of `taskpane.html`, and change the reference in the manifest at the same time. Not sure if the entry pane has to be called taskpane.

**Review by tobiasdiez — APPROVED** [review]
Nice!

I just tried to follow https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins to test if one could sideload the staged build in Word. However, the address in the manifest points to localhost and not to the (changing) azure staging address. Don't know what's the best way to fix this. The obvious choices of a) having a fixed staging web address or b) transforming the manifest during build to inject the correct address don't seem to be possible right now https://github.com/Azure/static-web-apps/issues/22 https://github.com/Azure/static-web-apps/issues/537. 
What could work is to use the output of the deployment https://github.com/Azure/static-web-apps-deploy/blob/0407e359a606e89151694428fa2457e4ef646693/action.yml#L44, transform the manifest file and then do another deployment including the new manifest. Sounds very awkward. Anyway, that's something for a new PR.

**Comment by mohit038** [comment]
> Transform the manifest file and then do another deployment, including the new manifest

We don't need to host the manifest file on the server. This file just points to the location where the addin is hosted. And this shared catalog folder thing is like a shared google drive folder that can only be shared with Windows users. So my suggestion is to create a google drive folder and put the updated manifest file in that folder so that everyone can access it.

And another advantage of using a drive folder is that even if our staging web address changes, we can easily update the web address in the manifest file. 

> I just tried to follow https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins to test if one could sideload the staged build in Word.

I tried it with the updated link, but I got an error because the addin is still not connected with jabref online. It should work after the API azure function is implemented.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> Edit: Sorry, I didn't know that link changes every time a commit is pushed, I'd suggest we have a stable link in that case if that's possible.

I think it just changes for every PR. I'll keep on looking at it but here are some links :stuck_out_tongue: 

* The deployment URL [has a specific form, only the PR number should change](https://docs.microsoft.com/en-us/azure/static-web-apps/review-publish-pull-requests#:~:text=if%20you%20take%20a%20closer%20look%20at%20the%20url%2C%20you%20can%20see%20that%20it's%20composed%20like%20this%3A%20https%3A%2F%2F%3Csubdomain-pull_request_id%3E.%3Cazure_region%3E.azurestaticapps.net.)
* More information about how to get the pull-id is in the link Tobas [provided above](https://github.com/Azure/static-web-apps/issues/22) and on the GitHub side in https://github.com/actions/checkout/issues/58
* Perhaps it is easier using something like https://github.com/marketplace/actions/find-current-pull-request

**Comment by tobiasdiez** [comment]
Ohh, I didn't realized that the URL is essentially constant except for the PR id. That's a super nice finding @k3KAW8Pnf7mkmdSMPHz27!

So in this case, the github action can indeed construct the correct path and inject it into the manifest file before uploading. Then one can simply test the PR by sideloading something like `https://lively-ground-0d7c50410-216.centralus.azurestaticapps.net/manifest.xml`

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Perhaps updating the manifest can be done with https://github.com/marketplace/actions/edit-xml

**Pull request merged**
