### PR TITLE
Add Test data in CSL JSON format

### PR DESCRIPTION
**Pull request by mohit038-zz**
Adds more test data in CSL JSON format.

### CODE REVIEW

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
In my opinion, most of the extension should use the data format of JabRef online (or a slightly modified version thereof depending on our needs. This is mainly because we control this format and thus can change it according to our use cases and evolve it in a consistent way across the whole platform (online, desktop, word extension, ...). For example, suppose you want to show the (jabref) group an entry belongs to in the sidepane. This is gona be hard since CSL doesn't have a field for such groups.
The only point were the data should be transformed to CSL is right before a citation string is created using the citeproc library. 

Thus I would vote to have the test-data also in JabRef's online format. What do you think?

**Comment by mohit038** [comment]
>  Suppose you want to show the (jabref) group an entry belongs to in the side pane. This is gonna be hard since CSL doesn't have a field for such groups. 

Data doesn't have to be in strictly CSL JSON format. [Only those fields that are essential for citation](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#introduction) should be in the correct CSL JSON format. It is completely fine if data has some extra fields.

**Comment by tobiasdiez** [comment]
Yes that's right, you could add custom fields that are simply ignored by CSL. But what is the advantage of using CSL-like data structures throughout the addon? You still need an adapter that transform the JabRef online format to the (custom) CSL format. For example, what happens if CSL decides to change their data format in the next version? Then the whole presentation layer of the addon would need to be changed as well to reflect this change. In my opinion, this would only make sense if we would use CSL also for the display of the entry in the sidepane.

By the way, here is a transformer from Bibtex > CSL: https://github.com/michel-kraemer/citeproc-java/blob/master/citeproc-java/src/main/java/de/undercouch/citeproc/bibtex/BibTeXConverter.java

**Comment by Siedlerchr** [comment]
We talked about this in the call and I think JabRef Online should be able to export/provide the data in CSL-JSON. So you could have multiple consumers. I would not do the transformation in the office addon.

**Comment by tobiasdiez** [comment]
That's a really good question, and I thought long about this. I think, I prefer if the Jabref online api is as streamlined as possible and don't provide 20 different output formats. Also the CSL-Json doesn't really fit well with the graphql spirit and I would probably need to remodel the CSL in graphql, which is quite some overhead. Also the word-addin is currently the only use case where the CSL as an output format would make sense. Instead, I propose that the JabRef online api is very close to the CSL specification, and then the word-addin has a simple transformer converting the api types to CSL. If in the future there is more demand in a CSL output, this transformer could then be released as a separate library to make it reusable. In my opinion, this is the most flexible and most maintanable approach. What do you think? That being said, the jabref online api is still very flexible, so if there are changes I can implement to make this transformation easier, please open an issue at the jabref online repo (e.g. I remember there were issues with the author format).

It also depends on what purpose the jabref online api serves. If it would be a general purpose api to get bibliographic metadata of all papers (eg like crossref), I would agree that CSL is a nice additional output format. However, for me, jabref-online is meant as an api for the jabref ecosystem - and there I find it more important that we keep the full flexibility to control every aspect of the api and adapt it based on our needs.

**Comment by mohit038** [comment]
Not needed anymore.

**Pull request closed without merging**
